Test für GUI mit WFA .NET Framework
Supergecki/LaTriX pull request #28
Opened 2024-07-20 15:02 UTC by Anasalzoabi

ich habe die GUI mit WFA .Net Framework gebaut .Um die Ausgabe automatisch zu aktualisieren, habe ich das Ereignis `CellValueChanged` für das `DataGridView`-Steuerelement verwendet.

2024-07-20 15:29 UTC, Supergecki requested changes
Diesen Code kann ich leider nicht ausführen. Liegt das daran, dass explizit .NET 4.8.1 getargetted wird? Das ist mittlerweile schon ein ganzes Stück veraltet, .NET 8+ wäre sinnvoll 😅 
Außerdem die GUI-spezifischen Dateien unbedingt aus dem root-Ordner rausnehmen! Das sind Quelltext-Dateien, die müssen auch im Quelltext-Ordner (`src`) liegen. Ich verstehe auch noch nicht ganz, wieso die Datei `LaTeXConverterClass.cs` kopiert wurde? Der Sinn des Packages ist ja, dass wir einfach eine Referenz auf das Package hinzufügen können und sich ein Paketmanager um die nötigen Installationen kümmert.

2024-07-20 16:31 UTC, Anasalzoabi commented
Ich habe auf die Version eigentlich nicht geachtet, danke für das Feedback.

Dieser gesamte Branch dient einfach zum Testen. Ich habe zuerst versucht, die LaTriXLib hinzuzufügen, aber das hat nicht funktioniert. Ich vermute, dass dies daran liegt, dass die .NET-Version sehr alt ist.
Ich werde die Version anpassen und es erneut pushen.

2024-07-20 21:56 UTC, Supergecki commented
So, jetzt baut es zumindest.
Die Grundfunktionalitäten scheinen gegeben zu sein, es tut das, was es tun soll.
Dadurch, dass es mit WFA gebaut wurde, sieht es natürlich etwas antiquiert aus, aber das sollte vorher in Ordnung sein. (Diesbezüglich unbedingt noch einmal dokumentieren, dass nun doch nicht mit Maui, sondern WFA gebaut wurde.)

Was mich bislang am meisten stört, ist, dass sich die Steuerelemente nicht in Position und Größe an die Fenstergröße anpassen (Fill-Optionen). Schaut man sich das Programm im Vollbildmodus an, so ist man durchaus enttäuscht über den vielen ungenutzten Fensterplatz. Hier müsste man die hartcodierten Werte im Designer-Programm überdenken und mögliche Fill-Optionen evaluieren. Genauso müsste "Nach LaTeX" und das zugehörige darunterliegende Pfeillabel (für welches sicherlich auch noch schönere Optionen als ein einfacher ASCII-Pfeil existieren) zentriert zwischen den Steuerelementen vorliegen.

Außerdem: Die Textbox für das Output ist noch nicht readonly gesetzt! Das muss unbedingt nachgeholt werden, weil es für den Nutzer überhaupt nicht vorgesehen ist, dort Eingaben zu tätigen.

2024-07-20 22:12 UTC, Anasalzoabi commented
Dank für dein Feedback.

In Bezug auf die Steuerelemente und ihre Anpassung an die Fenstergröße hast du völlig recht. Ich werde die vom Designer-Programm festgelegten Werte ändern und geeignete Fill-Optionen setzen. Auch die Zentrierung des "Nach LaTeX"-Labels und des zugehörigen Pfeillabels wird berücksichtigt.

Was die Ausgabetextbox betrifft: Das hatte ich eigentlich auf meiner TODO-Liste, aber beim Programmieren habe ich es leider vergessen.

2024-07-22 06:55 UTC, Supergecki requested changes
Okay, wir kommen in die richtige Richtung. Ein paar kleine Anmerkungen:

- [Dieser Commit](https://github.com/Supergecki/LaTriX/pull/28/commits/31d798a66de7c4fd70bc3212b2b84d4d8fc1b942) hätte eigentlich aufgespalten werden müssen, hier wurden zu verschiedene Probleme behoben (Fenstergröße, Pfeilanpassung und readonly-set). Das müsste für die Versionsverwaltung aufgespalten werden, weil hier sonst verschiedene Issues adressiert werden.
- Die Größe der Zellen passt sich jetzt zwar an die Containergröße an, nur hilft das wenig, wenn das Fenster zu klein startet, um alle Inhalte anzeigen zu können 😅 Hier entweder manuell das Startfenster vergrößern oder gleich im Vollbildmodus starten.
- [Diesen Commit](https://github.com/Supergecki/LaTriX/pull/28/commits/7248cbddd5093d23e00cf29a9bd29f64d97f8a4a) verstehe ich nicht, der LaTeXConverter gibt doch standardmäßig schon immer einen Punkt aus? Der Commit sollte überhaupt nicht nötig sein.

2024-07-22 08:33 UTC, Anasalzoabi commented
Danke, Martin, für dein Feedback.

* Du hast vollkommen recht, wir hätten den Commit von Anfang an aufspalten sollen. Ich werde in zukünftigen Commits darauf achten.
* Ich werde die Anwendung so ändern, dass sie im Vollbildmodus startet und im kleineren Modus auf eine Größe von 1200 x 1100 Pixeln eingestellt wird.
* Auch hier hast du recht. Der LaTeXConverter sollte standardmäßig die Punkte korrekt setzen. Ich habe eine Lösung implementiert, die sicherstellt, dass sowohl Kommas als auch Punkte korrekt zu Punkten umgewandelt werden.

2024-07-22 08:56 UTC, Supergecki commented
Das sieht jetzt gut aus, ich merge es.

2024-07-22 08:56 UTC, merged